// =============================================================================
// DrivioGo — Admin Mock Data
// Used for development while Supabase tables are not yet created.
// Replace with real Supabase calls when migrations are applied.
// =============================================================================

import type {
  Vehicle,
  PricingTable,
  ImportJob,
  AuditLog,
  AdminDashboardStats,
} from '@/types/admin';

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'v1',
    brand: 'Toyota',
    model: 'Corolla Cross',
    year: 2024,
    version: '2.0 GR-S CVT',
    category: 'SUV',
    transmission: 'CVT',
    fuel: 'FLEX',
    color: 'Branco Lunar',
    seats: 5,
    doors: 4,
    description: 'SUV compacto com design esportivo, tecnologia de ponta e conforto para o dia a dia.',
    features: ['Ar-condicionado digital', 'Câmera de ré', 'Central multimídia 9"', 'Sensor de estacionamento', 'Piloto automático adaptativo'],
    isActive: true,
    isFeatured: true,
    featuredOrder: 1,
    images: [
      { id: 'i1', vehicleId: 'v1', url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800', altText: 'Toyota Corolla Cross branco', displayOrder: 0, isMain: true },
    ],
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-03-01T08:00:00Z',
  },
  {
    id: 'v2',
    brand: 'Honda',
    model: 'HR-V',
    year: 2024,
    version: '1.5 Turbo EX CVT',
    category: 'SUV',
    transmission: 'CVT',
    fuel: 'GASOLINA',
    color: 'Prata Lunar',
    seats: 5,
    doors: 4,
    description: 'SUV com espaço generoso, tecnologia Honda Sensing e motor turbo eficiente.',
    features: ['Honda Sensing', 'Teto solar', 'Bancos em couro', 'Carregamento wireless', 'Apple CarPlay'],
    isActive: true,
    isFeatured: true,
    featuredOrder: 2,
    images: [
      { id: 'i2', vehicleId: 'v2', url: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800', altText: 'Honda HR-V prata', displayOrder: 0, isMain: true },
    ],
    createdAt: '2025-01-20T10:00:00Z',
    updatedAt: '2025-02-28T09:00:00Z',
  },
  {
    id: 'v3',
    brand: 'Volkswagen',
    model: 'T-Cross',
    year: 2024,
    version: '1.4 TSI Highline DSG',
    category: 'SUV',
    transmission: 'AUTOMATICO',
    fuel: 'GASOLINA',
    color: 'Azul Biscay',
    seats: 5,
    doors: 4,
    description: 'SUV compacto premium com motor TSI, câmbio DSG e acabamento Highline.',
    features: ['Faróis LED', 'Head-up display', 'Câmera 360°', 'Assistente de partida em rampa', 'Frenagem autônoma de emergência'],
    isActive: true,
    isFeatured: false,
    images: [
      { id: 'i3', vehicleId: 'v3', url: 'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800', altText: 'Volkswagen T-Cross azul', displayOrder: 0, isMain: true },
    ],
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2025-02-20T11:00:00Z',
  },
  {
    id: 'v4',
    brand: 'Hyundai',
    model: 'Creta',
    year: 2024,
    version: 'Ultimate 1.0 T-GDI',
    category: 'SUV',
    transmission: 'AUTOMATICO',
    fuel: 'GASOLINA',
    color: 'Vermelho Pulse',
    seats: 5,
    doors: 4,
    description: 'SUV moderno com design arrojado, tecnologia BlueLink e máximo conforto.',
    features: ['BlueLink conectado', 'Tela panorâmica 10.25"', 'Carregamento sem fio', 'SmartSense', 'Bancos ventilados'],
    isActive: true,
    isFeatured: true,
    featuredOrder: 3,
    images: [
      { id: 'i4', vehicleId: 'v4', url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800', altText: 'Hyundai Creta vermelho', displayOrder: 0, isMain: true },
    ],
    createdAt: '2025-02-10T10:00:00Z',
    updatedAt: '2025-03-05T10:00:00Z',
  },
  {
    id: 'v5',
    brand: 'Jeep',
    model: 'Renegade',
    year: 2024,
    version: 'Limited 1.3 T270 AT9',
    category: 'SUV',
    transmission: 'AUTOMATICO',
    fuel: 'FLEX',
    color: 'Preto Colorado',
    seats: 5,
    doors: 4,
    description: 'Jeep com estilo off-road, motor turbo flex e câmbio automático de 9 marchas.',
    features: ['4x4 Trail Rated', 'Uconnect 8.4"', 'Cruise control adaptativo', 'Selec-Terrain', 'Câmera de ré'],
    isActive: false,
    isFeatured: false,
    images: [
      { id: 'i5', vehicleId: 'v5', url: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800', altText: 'Jeep Renegade preto', displayOrder: 0, isMain: true },
    ],
    createdAt: '2025-01-05T10:00:00Z',
    updatedAt: '2025-01-30T14:00:00Z',
  },
  {
    id: 'v6',
    brand: 'Fiat',
    model: 'Pulse',
    year: 2024,
    version: 'Impetus 1.0 Turbo AT',
    category: 'SUV',
    transmission: 'AUTOMATICO',
    fuel: 'FLEX',
    color: 'Cinza Seduction',
    seats: 5,
    doors: 4,
    description: 'SUV compacto italiano com design exclusivo, tecnologia Connect Me e motor turbo.',
    features: ['Connect Me com Alexa', 'Painel 7"', 'Câmera de ré', 'Faróis full LED', 'Assistente de permanência em faixa'],
    isActive: true,
    isFeatured: false,
    images: [
      { id: 'i6', vehicleId: 'v6', url: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800', altText: 'Fiat Pulse cinza', displayOrder: 0, isMain: true },
    ],
    createdAt: '2025-02-20T10:00:00Z',
    updatedAt: '2025-03-10T09:00:00Z',
  },
];

export const MOCK_PRICING_TABLE: PricingTable = {
  id: 'pt1',
  name: 'Tabela Março 2026',
  description: 'Tabela de preços vigente para contratos iniciados em março de 2026.',
  isActive: true,
  createdAt: '2026-03-01T08:00:00Z',
  updatedAt: '2026-03-01T08:00:00Z',
  versions: [
    {
      id: 'ptv1',
      pricingTableId: 'pt1',
      versionNumber: 1,
      label: 'v1 — Inicial',
      notes: 'Primeira versão da tabela de março.',
      isActive: false,
      activatedAt: '2026-03-01T08:00:00Z',
      deactivatedAt: '2026-03-10T10:00:00Z',
      createdAt: '2026-03-01T08:00:00Z',
      createdById: 'admin1',
      createdByName: 'Maria Silva',
      rules: [],
    },
    {
      id: 'ptv2',
      pricingTableId: 'pt1',
      versionNumber: 2,
      label: 'v2 — Reajuste 10/03',
      notes: 'Ajuste nos valores de monitoramento.',
      isActive: true,
      activatedAt: '2026-03-10T10:00:00Z',
      createdAt: '2026-03-10T09:30:00Z',
      createdById: 'admin1',
      createdByName: 'Maria Silva',
      rules: [
        {
          id: 'r1',
          pricingTableVersionId: 'ptv2',
          vehicleId: 'v1',
          vehicleName: 'Toyota Corolla Cross',
          contractDurationMonths: 24,
          excessKmValue: 1.45,
          monitoringValue: 89.9,
          reserveCarValue: 149.9,
          kmOptions: [
            { id: 'k1', vehiclePricingRuleId: 'r1', annualKm: 10000, monthlyPrice: 2890 },
            { id: 'k2', vehiclePricingRuleId: 'r1', annualKm: 15000, monthlyPrice: 3050 },
            { id: 'k3', vehiclePricingRuleId: 'r1', annualKm: 20000, monthlyPrice: 3210 },
            { id: 'k4', vehiclePricingRuleId: 'r1', annualKm: 25000, monthlyPrice: 3390 },
            { id: 'k5', vehiclePricingRuleId: 'r1', annualKm: 30000, monthlyPrice: 3590 },
            { id: 'k6', vehiclePricingRuleId: 'r1', annualKm: 35000, monthlyPrice: 3820 },
            { id: 'k7', vehiclePricingRuleId: 'r1', annualKm: 40000, monthlyPrice: 4100 },
          ],
        },
        {
          id: 'r2',
          pricingTableVersionId: 'ptv2',
          vehicleId: 'v2',
          vehicleName: 'Honda HR-V',
          contractDurationMonths: 24,
          excessKmValue: 1.55,
          monitoringValue: 89.9,
          reserveCarValue: 149.9,
          kmOptions: [
            { id: 'k8', vehiclePricingRuleId: 'r2', annualKm: 10000, monthlyPrice: 3190 },
            { id: 'k9', vehiclePricingRuleId: 'r2', annualKm: 15000, monthlyPrice: 3380 },
            { id: 'k10', vehiclePricingRuleId: 'r2', annualKm: 20000, monthlyPrice: 3560 },
            { id: 'k11', vehiclePricingRuleId: 'r2', annualKm: 25000, monthlyPrice: 3760 },
            { id: 'k12', vehiclePricingRuleId: 'r2', annualKm: 30000, monthlyPrice: 3980 },
            { id: 'k13', vehiclePricingRuleId: 'r2', annualKm: 35000, monthlyPrice: 4220 },
            { id: 'k14', vehiclePricingRuleId: 'r2', annualKm: 40000, monthlyPrice: 4490 },
          ],
        },
      ],
    },
  ],
};

export const MOCK_IMPORT_JOBS: ImportJob[] = [
  {
    id: 'ij1',
    fileName: 'tabela-marco-2026-v2.xlsx',
    fileUrl: '/storage/imports/tabela-marco-2026-v2.xlsx',
    fileSize: 48320,
    status: 'SUCCESS',
    totalRows: 42,
    processedRows: 42,
    successRows: 42,
    errorRows: 0,
    createdById: 'admin1',
    createdByName: 'Maria Silva',
    startedAt: '2026-03-10T09:30:00Z',
    completedAt: '2026-03-10T09:30:45Z',
    createdAt: '2026-03-10T09:30:00Z',
    pricingTableVersionId: 'ptv2',
  },
  {
    id: 'ij2',
    fileName: 'tabela-marco-2026-v1.xlsx',
    fileUrl: '/storage/imports/tabela-marco-2026-v1.xlsx',
    fileSize: 47100,
    status: 'SUCCESS',
    totalRows: 40,
    processedRows: 40,
    successRows: 38,
    errorRows: 2,
    errorSummary: 'Linhas 12 e 23: valor de KM excedente inválido.',
    createdById: 'admin1',
    createdByName: 'Maria Silva',
    startedAt: '2026-03-01T08:00:00Z',
    completedAt: '2026-03-01T08:01:10Z',
    createdAt: '2026-03-01T08:00:00Z',
    pricingTableVersionId: 'ptv1',
  },
  {
    id: 'ij3',
    fileName: 'tabela-fev-2026.xlsx',
    fileUrl: '/storage/imports/tabela-fev-2026.xlsx',
    fileSize: 45800,
    status: 'FAILED',
    totalRows: 0,
    processedRows: 0,
    successRows: 0,
    errorRows: 0,
    errorSummary: 'Formato de arquivo inválido. Verifique se a planilha segue o modelo padrão.',
    createdById: 'admin2',
    createdByName: 'João Santos',
    startedAt: '2026-02-28T17:22:00Z',
    completedAt: '2026-02-28T17:22:05Z',
    createdAt: '2026-02-28T17:22:00Z',
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'al1',
    adminUserId: 'admin1',
    adminUserName: 'Maria Silva',
    action: 'ACTIVATE',
    entityType: 'PricingTableVersion',
    entityId: 'ptv2',
    entityLabel: 'Tabela Março 2026 — v2',
    createdAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'al2',
    adminUserId: 'admin1',
    adminUserName: 'Maria Silva',
    action: 'IMPORT',
    entityType: 'ImportJob',
    entityId: 'ij1',
    entityLabel: 'tabela-marco-2026-v2.xlsx',
    createdAt: '2026-03-10T09:30:00Z',
  },
  {
    id: 'al3',
    adminUserId: 'admin1',
    adminUserName: 'Maria Silva',
    action: 'UPDATE',
    entityType: 'Vehicle',
    entityId: 'v4',
    entityLabel: 'Hyundai Creta 2024',
    changes: {
      before: { isActive: false },
      after: { isActive: true },
    },
    createdAt: '2026-03-05T10:00:00Z',
  },
  {
    id: 'al4',
    adminUserId: 'admin2',
    adminUserName: 'João Santos',
    action: 'CREATE',
    entityType: 'Vehicle',
    entityId: 'v6',
    entityLabel: 'Fiat Pulse 2024',
    createdAt: '2026-02-20T10:00:00Z',
  },
  {
    id: 'al5',
    adminUserId: 'admin1',
    adminUserName: 'Maria Silva',
    action: 'DEACTIVATE',
    entityType: 'Vehicle',
    entityId: 'v5',
    entityLabel: 'Jeep Renegade 2024',
    createdAt: '2026-01-30T14:00:00Z',
  },
  {
    id: 'al6',
    adminUserId: 'admin1',
    adminUserName: 'Maria Silva',
    action: 'LOGIN',
    entityType: 'AdminUser',
    entityId: 'admin1',
    entityLabel: 'maria@driviogo.com',
    createdAt: '2026-03-17T08:15:00Z',
  },
];

export const MOCK_DASHBOARD_STATS: AdminDashboardStats = {
  totalVehicles: MOCK_VEHICLES.length,
  activeVehicles: MOCK_VEHICLES.filter((v) => v.isActive).length,
  inactiveVehicles: MOCK_VEHICLES.filter((v) => !v.isActive).length,
  activePricingTable: MOCK_PRICING_TABLE.name,
  activePricingVersion: 2,
  lastImport: MOCK_IMPORT_JOBS[0],
  recentAuditLogs: MOCK_AUDIT_LOGS.slice(0, 5),
};
